import { Children } from "react"

const backendDomain="http://localhost:8080"

const SummaryApi={
  SignUP:{
    url:`${backendDomain}/api/signup`,
    method:"post"
  },
  SignIN:{
    url:`${backendDomain}/api/signin`,
    method:"post"
  },
  Current_User:{
    url:`${backendDomain}/api/user-details`,
    method:"get"
  },
  logout_user:{
    url:`${backendDomain}/api/userLogout`,
    method:'get'
  },
  all_user:{
    url:`${backendDomain}/api/allUser`,
    method:'get'
  },
  updateUser:{
    url:`${backendDomain}/api/update-user`,
    method:"post"
  },
  uploadProduct:{
    url:`${backendDomain}/api/upload-product`,
    method:"post"
  },
  allProduct:{
    url:`${backendDomain}/api/get-product`,
    method:"get",
  },
  updateProduct:{
    url:`${backendDomain}/api/update-product`,
    method:"post"
  },
  categoryProduct:{
    url:`${backendDomain}/api/get-category`,
    method:"get"
  },
  categoryWiseProducts:{
    url:`${backendDomain}/api/category-products`,
    method:"post"
  },
  productDetails:{
    url:`${backendDomain}/api/get-product-details`,
    method:"post"
  },
  addToCartProduct:{
    url:`${backendDomain}/api/addtocart`,
    method:'post'
  },
  countAddToCartProduct:{
    url:`${backendDomain}/api/countaddtocartproduct`,
    method:'get'
  },
  viewAddToCart:{
    url:`${backendDomain}/api/view-add-to-cart`,
    method:'get'
  },
  updateCartProduct:{
    url:`${backendDomain}/api/update-cart-product`,
    method:'post'
  },
  deleteCartProduct:{
    url:`${backendDomain}/api/delete-cart-product`,
    method:"post"
  },
  searchProduct:{
    url:`${backendDomain}/api/search-product`,
    method:'get'
  },
  filterProduct:{
    url:`${backendDomain}/api/filter-product`,
    method:"post"
  },
  payment:{
    url:`${backendDomain}/api/checkout`,
    method:"post"
  }
}

export default SummaryApi